databases:
  - name: personal-task-manager-db
    databaseName: personal_task_manager
    user: task_manager_user
    plan: free

services:
  - type: web
    name: personal-task-manager-backend
    env: node
    plan: free
    buildCommand: npm install && node scripts/build-and-init.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: personal-task-manager-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000

  - type: web
    name: personal-task-manager-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: NODE_ENV
        value: production 